### ISSUE TITLE
Unique Realtime Data

### ISSUE THREAD

**Issue by Cloud-Dark** [solzimer/nsyslog#23]
I'm making a simple transport, where I want only when there is a new file, it is sent to my webhook. but why is what I receive always the same? isn't there something different?
I want it only when there is a new row to be sent to the server, if there isn't then it doesn't need to be sent to the server, this is my config.
please help me to fix this

```
{
	"config" : {
		"datadir" : "/tmp/nsyslog3"
	},

	"inputs" : {
		"file" : {
			"type" : "file",
			"config" : {
				"path" : "/var/log/syslog",
				"watch" : true,
				"readmode" : "offset",
				"offset" : "start"
			}
		}
	},

	"processors" : {
		"throttle" : {
			"type" : "throttle",
			"config" : {
				"format" : "${JSON}"
			}
		}
	},

	"transporters" : {
		"http" : {
			"type" : "http",
			"config" : {
				"url" : "https://webhook.site/ec35b3fc-16e6-40f1-aaef-1b1c19d193c9",
				"format" : "${originalMessage}",
				"method" : "post",
				"headers" : {
					"Content-Type" : "text/plain"
				}
			}
		}
	},

	"flows" : [
		{"from":"file", "processors":["throttle"], "transporters":"http"}
	]
}```

**Comment by solzimer** [comment]
Hi!

You need to change `"readmode" : "offset"` to `"readmode" : "watermark"` . This way, the reader will keep track of the current position of the read data, and will only read the new added content.

**Comment by Cloud-Dark** [comment]
solved, thanks
